config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from rest_framework.routers import DefaultRouter
from taskist.blog import views as blog_views
from taskist.users import views as users_views

router = DefaultRouter()
router.register(r'posts', blog_views.PostViewSet)
router.register(r'users', users_views.UserViewSet)

# router.register(r'groups', views.GroupViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^api/', include(router.urls)),
]

urlpatterns += [url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
                url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),
                url(r'^admin/', include(admin.site.urls)),
                url(r'^users/', include("taskist.users.urls", namespace="users")),
                url(r'^blog/', include("taskist.blog.urls", namespace="posts")),
                url(r'^accounts/', include('allauth.urls'))] + static(settings.MEDIA_URL,
                                                                      document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', 'django.views.defaults.bad_request'),
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error')
    ]

taskist/blog/urls.py
from django.conf.urls import url
from taskist.blog import views

urlpatterns = [
    url(
        regex=r'^posts/$',
        view=views.PostListView.as_view(),
        name='list'
    ),
    url(
        r'^post/$', views.PostFormView.as_view()
    ),
    url(
        r'^post_card/$', views.PostCardView.as_view()
    )
]

taskist/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

taskist/blog/models.py
__author__ = 'chedv13'

from django.db import models
from taskist.users.models import User
from django.contrib import admin


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='blog/posts/images/%Y/%m/%d', blank=True, null=True)
    user = models.ForeignKey(User)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']


class PostAdmin(admin.ModelAdmin):
    list_display = ('title', 'content', 'user_id', 'image')


admin.site.register(Post, PostAdmin)

taskist/common/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from taskist.users.models import User
from mptt.models import MPTTModel, TreeForeignKey


class Comment(MPTTModel):
    text = models.TextField(default='')
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    user = models.ForeignKey(User)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)

    class Meta:
        ordering = ['-created_at']


class Like(models.Model):
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    user = models.ForeignKey(User)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

taskist/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from easy_thumbnails.fields import ThumbnailerImageField


@python_2_unicode_compatible
class User(AbstractUser):
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    # TODO: Разобраться с генерилкой тамбнейлов
    avatar = ThumbnailerImageField(upload_to='users/users/images/%Y/%m/%d', blank=True, null=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

taskist/blog/forms.py
from django import forms
from django.utils import six
from djangular.forms import NgDeclarativeFieldsMetaclass, NgModelFormMixin


class PostForm(six.with_metaclass(NgDeclarativeFieldsMetaclass, NgModelFormMixin, forms.Form)):
    title = forms.CharField(max_length=200)

taskist/blog/views.py
__author__ = 'chedv13'

from taskist.blog.models import Post
from taskist.blog.serializers import PostSerializer
from rest_framework import viewsets
from django.views.generic import ListView, TemplateView
from taskist.blog.forms import PostForm


class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer


class PostListView(ListView):
    model = Post


class PostFormView(TemplateView):
    template_name = 'blog/post_form.html'

    def get_context_data(self, **kwargs):
        context = super(PostFormView, self).get_context_data(**kwargs)
        context.update(post_form=PostForm())

        return context


class PostCardView(TemplateView):
    template_name = 'blog/post_card.html'

    def get_context_data(self, **kwargs):
        context = super(PostCardView, self).get_context_data(**kwargs)

        return context

taskist/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .models import User
from rest_framework import viewsets
from taskist.users.serializers import UserSerializer


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

taskist/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en" ng-app="taskist">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}taskist{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
        <!-- Latest compiled and minified CSS -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        {#        <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">#}

        <!-- Optional theme -->
        <link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
        {#        <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">#}

        <!-- Your stuff: Third-party css libraries go here -->
        <link href="{% static 'semantic-ui/dist/semantic.min.css' %}" rel="stylesheet">
        <!-- This file store project specific CSS -->
        <link href="{% static 'css/project.css' %}" rel="stylesheet">
        {#        <link href="{% static 'css/semantic.min.css' %}" rel="stylesheet">#}
    {% endblock %}

    {% block angular %}
        <script src="{% static 'js/vendor/angular.min.js' %}"></script>
        <script src="{% static 'js/vendor/angular-route.min.js' %}"></script>
        <script src="{% static 'js/vendor/angular-resource.min.js' %}"></script>
        <script src="{% static 'js/vendor/angular-deckgrid.js' %}"></script>
    {% endblock %}

</head>

<body ng-controller="CommonController">

<div class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">taskist</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'home' %}">Главная</a></li>
                <li><a href="{% url 'about' %}">О приложении</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'users:detail' request.user.username %}">{% trans "My Profile" %}</a></li>
                    <li><a href="{% url 'account_logout' %}">{% trans "Logout" %}</a></li>
                {% else %}
                    <li><a href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a></li>
                    <li><a href="{% url 'account_login' %}">{% trans "Log In" %}</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

<div class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    {% endif %}

    {% block content %}
        <div class="row" ng-view></div>
    {% endblock content %}
</div>
<!-- /container -->

{% block modal %}{% endblock modal %}

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block javascript %}
    <!-- Latest JQuery -->
    <script src="{% static 'js/vendor/jquery-2.1.4.min.js' %}"></script>

    <!-- Latest compiled and minified JavaScript -->
    {#    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>#}
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <!-- Your stuff: Third-party javascript libraries go here -->
    {#    <script src="{% static 'js/semantic.min.js' %}"></script>#}
    <script src="{% static 'semantic-ui/dist/semantic.min.js' %}" rel="stylesheet"></script>

    <!-- place project specific Javascript in this file -->
    <script src="{% static 'js/project.js' %}"></script>

    <script src="../static/js/app.js"></script>
    <script src="../static/js/providers/post.js"></script>
    <script src="../static/js/controllers/common.js"></script>
    <script src="{% static 'js/controllers/main.js' %}"></script>
{% endblock javascript %}
</body>
</html>
 

taskist/templates/blog/post_card.html
<!-- ng-repeat="post in posts.data" -->
<div class="ui card">
    <div class="content">
        <div class="right floated meta">14h</div>
        <img class="ui avatar image" ng-src="{$ card.user.avatar $}">
        &nbsp;&nbsp;
        {$ card.title $}
    </div>
    <div class="image">
        <img ng-src="{$ card.image $}">
    </div>
    <div class="content">
        <span class="right floated">
            <i class="heart outline like icon"></i>
            17 likes
        </span>
        <i class="comment icon"></i>
        3 comments
    </div>
    <div class="content">

    </div>
    <div class="extra content">
        <div class="ui large transparent left icon input">
            <i class="heart outline icon"></i>
            <input type="text" placeholder="Add Comment...">
        </div>
    </div>
</div>

taskist/templates/blog/post_form.html
<form name="post_form">
    {{ post_form }}
</form>

taskist/templates/blog/post_list.html
<div>
    <div class="deckgrid posts main" deckgrid="" source="posts"
         cardTemplate="/blog/post_card"></div>
</div>

taskist/templates/index.html
{% extends "base.html" %}

{% block title %}Server Error{% endblock %}

{% block content %}
    <h1>Ooops!!! 500</h1>

    <h3>asdhjakshdjkh</h3>

    <p>We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try
        refreshing.</p>
{% endblock content %}

taskist/templates/index2.html
asasdshadjhjshdj

taskist/templates/pages/about.html
{% extends "base.html" %}

taskist/templates/pages/home.html
{% extends "base.html" %}

taskist/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12 ">
    <a class="btn btn-primary" href="{% url 'users:update' %}">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

taskist/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
    <h1>{{ user.username }}</h1>
    <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Update</button>
          </div>
        </div>
    </form>
{% endblock %}

taskist/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Members{% endblock %}

{% block content %}

<div class="container">

    <h2>Users</h2>

    <div class="list-group">
        {% for user in user_list %}
          <a href="{% url 'users:detail' user.username %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ user.username }}</h4>
          </a>
        {% endfor %}

    </div>

{% endblock content %}

taskist/templates/views/main.html
<div class="ui card" ng-repeat="post in posts">
    <div class="image">
        <img src="{$ post.attributes.image $}">
    </div>
    <div class="content">
        <a class="header">Kristy</a>

        <div class="meta">
            <span class="date">Joined in 2013</span>
        </div>
        <div class="description">
            {$ post.attributes.title $}
        </div>
    </div>
    <div class="extra content">
        <a>
            <i class="user icon"></i>
            22 Friends
        </a>
    </div>
</div>

{#{% for o in posts %}#}
{#    <div>{{ o }}</div>#}
{#    {$ test $}#}
{#{% endfor %}#}